### ISSUE TITLE
App building error when trying beta.4 with ng build

### ISSUE THREAD

**Issue by kolkov** [ui-router/ng2#11]
Hi!I have this error when trying beta.4
![image](https://cloud.githubusercontent.com/assets/3740898/21073814/5283f9d4-befa-11e6-89e9-cb0077064bfa.png)
What's wrong?
I builded ng2 from sources. All built without errors.

**Comment by kolkov** [comment]
Building complete after copying just js.js to core.

**Comment by christopherthielen** [comment]
fixed in beta.4 release
