### ISSUE TITLE
Relative child-routing

### ISSUE THREAD

**Issue by niwrA** [ui-router/ng2#16]
The tutorial ends with suggesting that you can use .person instead of people.person for relative addressing. I could not get this to work however (it works otherwise). Is that a bug? Or am I just missing something?

**Comment by christopherthielen** [comment]
I just checked the plunker and it actually does use relative links:

```html
          <li *ngFor="let person of people">
            <a uiSref=".person" [uiParams]="{ personId: person.id }">
              {{person.name}}
            </a>
          </li>
```

What troubles are you having?

**Comment by niwrA** [comment]
I have to use people.person, or it simply won't work. 

My biggest problem right now though, which may make me return to regular Angular 2 routing, is that the angular cli can't compile with the UIRouter.ForRoot() line in there. If I add it back after ng serve it runs fine. Also, when I enter a route in the address bar, it doesn't work. Only the routing through uiSref links works at the moment. Presumably I'm overlooking something.

**Comment by kolkov** [comment]
HI! Try this temporary solution for Angular cli https://github.com/ui-router/ng2/pull/13

**Comment by zurie** [comment]
@niwrA you should try this in your UI Router Config

`import {UIRouter} from "ui-router-ng2";
import {Injectable} from "@angular/core";

@Injectable()
export class MyRootUIRouterConfig {
  constructor(uiRouter: UIRouter) {
    uiRouter.urlMatcherFactory.strictMode(false);
    uiRouter.urlMatcherFactory.caseInsensitive(true);

  }
}
`

**Comment by christopherthielen** [comment]
There is now a [full sample app](https://github.com/ui-router/sample-app-ng2) built with the Angular-CLI.

**Comment by kolkov** [comment]
Thank You very much for your work, @christopherthielen!
