### ISSUE TITLE
[Angular universal] page flicker when client side is loaded

### ISSUE THREAD

**Issue by aitboudad** [ui-router/ng2#18]
This due to the usage of [setTimeout](https://github.com/ui-router/ng2/blob/master/src/ng2/providers.ts#L156), removing it solve the issue

**Comment by christopherthielen** [comment]
I think the setTimeout is necessary, so the router instance is constructed when the NgModules are configured.  I'll take a look.

**Comment by aitboudad** [comment]
try moving this part to [APP_INITIALIZER](https://angular.io/docs/ts/latest/api/core/index/APP_INITIALIZER-let.html)

**Comment by aitboudad** [comment]
see https://github.com/ui-router/ng2/issues/43#issuecomment-278976233 let me know if you need a working example.

***Note***: I prefer waiting until angular/angular#13822 is done

**Comment by aitboudad** [comment]
I solved the page flicker by using `APP_INITIALIZER`:
```ts
export function onReady($transition: TransitionService) {
    return () => new Promise(resolve => {
        let eventHooks = [];
        ['onSuccess', 'onError'].map(hook => {
            const unsubscriberEventHook = $transition[hook]({}, (transition) => {
                eventHooks.map(unsubscriber => unsubscriber());
                resolve();
            });
            eventHooks.push(unsubscriberEventHook);
        });
    });
}

@NgModule({
    imports: [ ... ],
    providers: [
        {
            'provide': APP_INITIALIZER,
            'useFactory': onReady,
            'deps': [TransitionService],
            'multi': true,
        },
    ],
    bootstrap: [UIView],
})
```

**Comment by christopherthielen** [comment]
@aitboudad did you close this issue because you think it's better to wait for ng 4, or because you solved it manually with ng2?  Do you think APP_INITIALIZER is something UI-Router should provide by default?  It looks pretty trivial to implement.

**Comment by aitboudad** [comment]
I think it's better to wait for ng4 :)
