### ISSUE TITLE
Empty links by ng2 `uiSref` directive

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/ng2#26]
_From @artaommahe on January 8, 2017 20:16_

`uiSref` directives binds `'null'` string to `href` on provided `null` or empty string `''` state.

current behavior
```html
<!-- template -->
<a [uiSref]="null">smth</a>
<a [uiSref]="''">smth</a>

<!-- result -->
<a href="null">smth</a>
```

expected no `href` attribute (null property value?)
```html
<!-- result -->
<a>smth</a>
```

It's required for dynamic links when for some cases `href` should be empty and link clicks does not trigger any state changes (access rights check e.x.)

_Copied from original issue: angular-ui/ui-router#3248_

**Comment by christopherthielen** [comment]
_From @artaommahe on January 9, 2017 20:16_

Fixed expected result html, due to empty href forced to reload page

**Comment by gcca** [comment]
I created a PR. But the bug cannot be shown on unit test with PhantomJS (unlike Firefox or Chrome launcher).

**Comment by rochapablo** [comment]
None of this is working:

```
<li *ngFor="let item of items">
   <a [uiSref]="item.link">{{ item.title }}</a>
   <a uiSref="item.link">{{ item.title }}</a>
   <a uiSref=".link">{{ item.title }}</a>
</li>
```

What could I be doing wrong?

**Comment by rochapablo** [comment]
Never mind, the problem was my items links which was

```
[
   { link: '/stores', title: 'Stores' }
]
```

Just removed the */* and all worked.
