### ISSUE TITLE
[beta.4][Ng2LocationServices] take account of APP_BASE_HREF

### ISSUE THREAD

**Issue by aitboudad** [ui-router/ng2#32]
Ng2LocationServices doesn't take account of `APP_BASE_HREF` which produce `Maximum call stack size exceeded exception
```
<base href="/app/">
```
![selection_064](https://cloud.githubusercontent.com/assets/1753742/22198037/96a70aa6-e14c-11e6-91be-9e4029c5a627.png)

**Comment by christopherthielen** [comment]
Thanks; I'll release a beta.5 ASAP.

Closed by #33

**Comment by aitboudad** [comment]
@christopherthielen wait #33 doesn't solve this issue

**Comment by aitboudad** [comment]
@christopherthielen see #34

**Comment by christopherthielen** [comment]
Oh, I see :) Thanks, I'll take a look at the new PR.
