### ISSUE TITLE
Uncaught TypeError: d.UIRouterRx is not a constructor

### ISSUE THREAD

**Issue by trumbitta** [ui-router/ng2#49]
After upgrading from `1.0.0-beta.3` to `1.0.0-beta.4`, the application breaks and I have this error in console:

`Uncaught TypeError: d.UIRouterRx is not a constructor`

Note: I thought UIRouterRx was an optional plugin, but then I found it imported and configured in `src/providers.ts` and now I'm confused.

**Comment by christopherthielen** [comment]
ui-router-rx is a non-optional dependency.

Before beta.4 it was "baked in" to ui-router-ng2.  In https://github.com/ui-router/ng2/commit/b0a672fa5e89dda8152ecab171b29b9326aced6f I moved the code to [its own project](https://github.com/ui-router/rx) and refactored it to be a ui-router plugin.

The dependency should automatically get included [because of the dependency in package.json](https://github.com/ui-router/ng2/blob/1.0.0-beta.4/package.json#L43)

**Comment by christopherthielen** [comment]
Follow up questions:

Are you using angular-cli? Webpack? SystemJS? UMD Bundles?  

How did you update to beta.4?  `npm install ui-router-ng2@1.0.0-beta.4`?

**Comment by trumbitta** [comment]
Thanks for the prompt reply :)

I was coming back to add that the application is an hybrid one via `ng1-to-ng2`.

I already verified the dependency gets installed inside `node_modules`.

Answers to your questions: latest Webpack 1.x, and updated to beta.4 changing the version number in package.json then `npm prune && npm install`.

**Comment by christopherthielen** [comment]
I see.  The ng1-to-ng2 story is going to change soon.  

In beta.3, we were building ng1 and ng2 code from a mono-repository. We split the repositories out for beta.4.  We also separated the release cycles (so ng1 has rc.1, while ng2 has beta.4).  

The ng1-to-ng2 code will have to change to address this.  We will have "blessed" combinations of ng1-to-ng2, ui-router-core, angular-ui-router, and ui-router-ng2 when we release a new ng1-to-ng2. 

ng1-to-ng2 currently is tied to the beta.3 releases.  It will not work until it's updated for the new split repositories/projects.  This shouldn't be terribly difficult, but I want to release ui-router-ng2 beta.5 first.

If you'd like to help with ng1-to-ng2, I've got the code compiling again.  You could try building from master if you like.  The story shouldn't change much for webpack/bundler users, but the UMD bundles will be changing significantly (all the ui-router libs -- core, ng1, ng2, rx -- will be bundled together)

**Comment by trumbitta** [comment]
I've got an hour or so, so I'm going to try to build it from master. I'll get back to you as soon as I have something to report 👍

**Comment by christopherthielen** [comment]
I'm just about to commit the updates to ng1-to-ng2

**Comment by christopherthielen** [comment]
and done 👍

**Comment by trumbitta** [comment]
Getting `Error: Error at app/app.module.ts:12:51: Cannot find module 'ui-router-ng1-to-ng2'.` at startup.

package.json: `"ui-router-ng1-to-ng2": "git+https://github.com/ui-router/ng1-to-ng2.git#4e1050e0af77462d5bffad238b37a7d649052006",`

**Comment by christopherthielen** [comment]
I know what the problem is.  That project needs a "prepublish" step for installs like that to work.  Give me a few minutes to write one.

**Comment by christopherthielen** [comment]
Try again.  

Also, I'm on gitter at https://gitter.im/angular-ui/ui-router might be easier to chat about this

**Comment by trumbitta** [comment]
Status update for passers-by: after a few failed attempts on my end, we decided it would be better if I just wait for the upcoming new release of ng1-to-ng2 before updating to 1.0.0.beta-4 :)
