### ISSUE TITLE
Double transition with async route resolver

### ISSUE THREAD

**Issue by lexigren** [ui-router/ng2#52]
version: 1.0.0-beta.4
For some reason in newly created angular-cli project, if resolver returns promise that resolves asynchronously, second transition to same state appearing without waiting for promise result.

```
export function twoRouteResolver() {
  return new Promise(resolve => {
    setTimeout(() => {
      console.log('%cchecking', 'color:red;');
      console.log('resolving');
      resolve();
    }, 1000);
  });
}
```

Without timeout second transition does not appear.

Demo: 
https://github.com/lexigren/UIRouterResolverProblemDemo

**Comment by christopherthielen** [comment]
Thanks for the demo. I'll look into this before releasing the next beta.

**Comment by christopherthielen** [comment]
This is due to https://github.com/angular/angular/issues/7908 

The `HashLocationStrategy` invokes the registered `onPopState` callback for both the `popState` and `hashChange` events.  This causes two transitions to be initiated.
