### ISSUE TITLE
Failed to navigate to a different state when defined with base URL and `otherwise` path

### ISSUE THREAD

**Issue by pengx17** [ui-router/ng2#56]
# How to reproduce

- Save a local copy of the official helloworld app
  - https://ui-router.github.io/ng2/tutorial/helloworld
- Move all files to a subfolder, e.g., `{home}/sub`
- add `<base href="/sub/">` to `index.html`
- turn off useHash for `UIRouterModule.forRoot` and add an `otherwise` rule `{  }`
  ```js
  @NgModule({
  imports: [ 
    BrowserModule,
    UIRouterModule.forRoot({ states: [ helloState, aboutState ], otherwise: { state: 'hello' } })
  ],
  declarations: [ App, Hello, About ],
  bootstrap: [ App ]
  })
  class RootAppModule {}
  ```
- serve the app from `{home}/` and go to the local app. The `hello` state can be successfully redirected, but when I click the `about` link, nothing happens (should expect to navigate to `about` state).

The issue does not occur either when there is no base url or `otherwise` rule.

**Comment by christopherthielen** [comment]
I believe this will be fixed in the next release by https://github.com/ui-router/ng2/commit/b858bd6f9d855a842f6f29d4bad056430b74f5ba

**Comment by christopherthielen** [comment]
Confirmed, it works when built off ui-router-core/master and ui-router-ng2/master.

https://gist.github.com/christopherthielen/1a27f76c352e97d871cd726d0a4f2efd

**Comment by kolkov** [comment]
Confirmed! 
Solved with beta.5!
