### ISSUE TITLE
Lifecycle Callbacks

### ISSUE THREAD

**Issue by s001dxp** [ui-router/ng2#6]
I want to be able to check if a user is authenticated and/or authorized to visit a view state before each transition to a new view/state. The default angular router has a 'canActivate' feature that is run before the app transitions to a new view.

How can I achieve the same using ui-router? I've searched the docs, the codebase here, and the web but have not found anything.

Thanks for your help

**Comment by richdyang** [comment]
You can use resolve in the state declaration or register a callback of TransitionService: onStart(..), onEntering(..), ...

**Comment by christopherthielen** [comment]
As @richdyang mentioned, use (for example) an [onStart hook](https://ui-router.github.io/ng2/docs/latest/classes/transition.transitionservice.html#onstart)

You can make a global hook which is triggered based on metadata stored on the state.

```
router.transitionService.onStart({ to: state => state.data && state.data.requiresAuth }, function(transition: Transition) {
  userSvc: UserService = transition.injector().get(UserService);
  if (!userSvc.authenticated()) {
    return router.stateService.target('login');
  }
});
```

**Comment by kolkov** [comment]
https://github.com/angular-ui/ui-router/issues/2964
