### ISSUE TITLE
Rejecting a transition that lazyLoad a module still load the module

### ISSUE THREAD

**Issue by Pirfox** [ui-router/ng2#60]
When we declare a state with lazyLoad it end up getting the module even if we stop / supersed the transition. 
Shouldn't the lazyLoad wait for the onbefore being resolved?

This is a simple example that i use with a login state and a top state protected by a transitionHook that redirect to the login if we aren't authenticated.
```
let login = {name: 'login', url: '/login', component: AuthComponent};
let top = {name: 'top', url: '/', component: AuthComponent};
let user = {name: 'top.user.**', url: 'user', loadChildren: () => System.import('./app/user.module.ts')};



export function requireAuthentication(transition: Transition) {
  let $state = transition.router.stateService;
  return $state.target('login');
}

export function uiRouterConfigFn(router: UIRouter) {
  // Use ui-router-visualizer to show the states as a tree
  // and transitions as a timeline
  visualizer(router);

   let authCriteria = {to: 'top.**'};
   router.transitionService.onBefore(authCriteria, requireAuthentication);
}

@NgModule({
  imports: [
    BrowserModule,
    UIRouterModule.forRoot({
            states: [login, top,user],
            config: uiRouterConfigFn
        }),
  ],
  declarations: [
    AppComponent,
    AuthComponent
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

```
let user = {    name: 'top.user',    url: 'user',    component: UserComponent};

@NgModule({
    imports: [
        UIRouterModule.forChild({
            states: [user]
        })
    ],
    declarations: [
        UserComponent
    ]
})
export default class UserModule {}
```

When you go to the future state you end up getting rejected to the login, but the module is still loaded. And you get an error for the transition being superseded by a different transition.
This error doesn't happen if we aren't using lazyLoading ( Or is silenced)

You can see the example on this plunker :https://plnkr.co/edit/RR2tABzqH26p75gPbnuE

**Comment by christopherthielen** [comment]
[The lazy load hook *is a priority 0 onBefore hook*](https://github.com/ui-router/core/blob/612d2e1e9bfa00e6bdfe9e34fc473684bc7ac33e/src/hooks/lazyLoad.ts#L69-L70).  We may want to make it a slightly lower priority hook (-100 or something).

You can make your hook slightly higher priority for now:

```js
   let authCriteria = {to: 'top.**'};
   router.transitionService.onBefore(authCriteria, requireAuthentication, { priority: 1 });
```

**Comment by Pirfox** [comment]
Thanks for the answer, I did not see the priority option to order the transitions hooks (my bad).
It is good for me at the moment since I can avoid the lazyLoad.
