### ISSUE TITLE
Parameters implicitly have an 'any' type

### ISSUE THREAD

**Issue by Mocha--** [ui-router/ng2#61]
Hi,

I just got some errors when I imported { UIRouterModule } from 'ui-router-ng2'(please see the attachment). 
![ui-router-error](https://cloud.githubusercontent.com/assets/8860999/23536902/6c8cc96a-001c-11e7-96db-93f7184f668f.png)

If anyone knows what happened, please help me.

Thanks,

**Comment by elboman** [comment]
Hi,
The core lib has few values which are implicitly of type `any`. I guess your `tsconfig` doesn't allow implicit `any` values, hence the error.

In fact this problem also appears in the react version: ui-router/react#29

A temporary solution would be to set `"noImplicitAny": false` in your config. The long term solution is to make a PR for the core to explicitly set those values to `any`.

**Comment by christopherthielen** [comment]
there's also `skipLibCheck` in typescript 2.x https://www.typescriptlang.org/docs/handbook/compiler-options.html

We intend to make the lib `noImplicitAny` compatible.  We just need to add a little bit of tooling that does the check before we publish.

**Comment by Mocha--** [comment]
Thanks, help a lot.

I'll close this issue.
