### ISSUE TITLE
Cannot install via yarn

### ISSUE THREAD

**Issue by marshall007** [ui-router/ng2#66]
The `"engine": { "node": ">6" }` restriction prevents `yarn` from installing the package. Apparently `npm` does not strictly enforce this check and just warns you instead (see https://github.com/yarnpkg/yarn/issues/634). `>=6.0.0` is probably what was actually intended here. It seems like the current `>6` syntax translates to requiring `v7.x+`.

**Comment by christopherthielen** [comment]
Thanks!
