### ISSUE TITLE
beta5 build fails

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/ng2#71]
Hi, I'm trying to build latest beta5 but build fails with the following
> ui-router-ng2@1.0.0-beta.5 clean /Users/marcin/Sites/uirouter-ng2
> shx rm -rf lib lib-esm _bundles _dec

Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:40:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:40:46: Cannot find name 'keyof'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:40:52: '=' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:42:46: A parameter initializer is only allowed in a function or constructor implementation.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:42:56: Cannot find name 'keyof'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:42:62: '=' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:58:42: Cannot find name 'Partial'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:99:22: Cannot find name 'Partial'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/jasmine/index.d.ts:99:35: Cannot find name 'Partial'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:244:13: Duplicate identifier '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:244:16: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:246:25: Cannot find name 'Partial'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:248:19: Duplicate identifier '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:366:39: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:2083:24: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5636:44: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5643:44: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5650:44: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5657:44: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5690:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5699:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5706:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5713:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5722:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5729:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5736:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5745:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5752:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5759:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5768:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5775:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:5782:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:9: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:10: Cannot find name 'P'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:15: Cannot find name 'keyof'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:21: ']' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:21: Cannot find name 'T'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:22: ';' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:23: Declaration or statement expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:26: A parameter initializer is only allowed in a function or constructor implementation.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:31: Cannot find name 'T'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:33: ']' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:34: ')' expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:35: Declaration or statement expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:37: Declaration or statement expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11502:40: Cannot find name 'boolean'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11511:29: Cannot find name 'ConformsPredicateObject'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:11522:42: Cannot find name 'ConformsPredicateObject'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:12762:29: Cannot find name 'object'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15452:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15461:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15494:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15503:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15538:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15547:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15580:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15589:12: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15622:22: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15629:22: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15662:24: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15669:24: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15685:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15694:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15704:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15714:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15724:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15734:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15744:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15754:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15789:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15797:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15804:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15836:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15844:21: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15851:21: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15914:21: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15914:37: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:15930:21: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16591:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16601:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16611:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16680:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16689:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16698:33: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16758:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16767:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16777:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16787:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16797:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16807:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16817:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16827:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16846:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16855:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16864:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16874:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16882:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16892:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16900:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16922:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16932:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16942:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16953:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16962:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16973:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:16982:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17139:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17147:21: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17154:21: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17170:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17179:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17188:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17197:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17207:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17215:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17225:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17233:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:17984:39: Cannot find name 'TemplateSettings'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18604:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18612:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18734:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18742:19: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18751:47: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18760:47: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18876:31: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18913:43: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18920:43: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18927:43: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18934:43: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18941:43: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18953:40: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18960:40: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18967:40: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18974:40: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18981:40: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:18993:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19000:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19007:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19014:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19021:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19032:39: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19072:53: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19079:58: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19086:58: Cannot find name 'Many'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19246:22: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19270:22: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19293:23: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19316:23: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19339:21: Cannot find namespace '_'.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19499:1: Declaration or statement expected.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19507:15: All declarations of 'WeakMap' must have identical type parameters.
Error at /Users/marcin/Sites/uirouter-ng2/node_modules/@types/lodash/index.d.ts:19507:33: Cannot find name 'object'.

**Comment by kolkov** [comment]
Hi! This may be helped:
https://github.com/ui-router/ng2/issues/58

**Comment by mkoczorowski** [comment]
solved thanks!
