### ISSUE TITLE
Angular4  <template> element is deprecated

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/ng2#73]
There is a waring in angular 4:

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    [WARNING ->]<template #componentTarget></template>
    <ng-content *ngIf="!componentRef"></ng-content>
  "): ng:///UIRouterModule/UIView.html@1:4

**Comment by christopherthielen** [comment]
Thank you.  This should be fixed in https://github.com/ui-router/ng2/pull/68/files
