### ISSUE TITLE
How to get queryParams

### ISSUE THREAD

**Issue by kolkov** [ui-router/ng2#9]
Hi! How to get queryParams in our ui-router-ng2 like in native router?
```
  ngOnInit() {
    this.route.queryParams
        .map((params: Params) => params['code'])
        .flatMap((code: string) => this.authService.exchange(code))
        .map((success: boolean) => success ? this.succeed() : this.fail())
        .subscribe();
  }
```
From this request for example:
`http://mydomain.com/facebook?code=AQBDRKsrmT4iyYZ1bOOEpncXNcor0584NW8MYLj-VaEyGhBoQ6Iup8PHWjPFK7V2PUaZ7zwreyEh9F8tpENJQLbpKqTENVOwEP2Xetddj7h-rLHc_3wzYaefbP0VetK29NknI1UDtQiOoCvdR7-lQhUI5f24FS5iVyr4azTH4ef5OXhFmNfsNHn23Jo2ngkj3XrEgDbrPs8L61d33U0Vejy02PmVElF6c42_OAsB4P5XCmYqC9yYWBXabQiVPSr1Zn4mC7rnqoDOm0T40nDLH4IK61QgeoSkmQqkpC0ze1S7qc6xAyG39PPqvFxgCnEOR1fBLRQwFyFa57mltIEUR5-J&state=thisshouldberandom#_=_`

**Comment by kolkov** [comment]
How to handle facebook redirects when using `#`?
```
UIRouterModule.forRoot({
      //states: MAIN_STATES,
      otherwise: { state: 'public.home', params: {} },
      useHash: true,
      configClass: MyUIRouterConfig
    }),
```

**Comment by christopherthielen** [comment]
Query parameters must be defined on the state's url like 
```js
{ name: 'facebook', url: '/facebook?code', component: FBCmp }
```

**Comment by kolkov** [comment]
Thanks! Please improve docs)
